# This is a basic workflow that is manually triggered

name: Mise à jour des programmes TV

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  schedule:
    - cron: "30 5 * * *" # Runs at 05:30 AM (UTC) 
 
jobs:
  # This workflow contains a single job called "greet"
  TV:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Installation de PHP et des extentions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl, zip, mbstring, xml, json  
        
    - name: Mise à jour des programmes
      run: php example/script_all.php 
      
    - name: Sauvgarde XML sur serveur
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.pass }}
        port: "22"
        source: "./var/export/xmltv.xml"
        target: "/var/www/xmltv"
        
    - name: Sauvgarde XML.GZ sur serveur
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.pass }}
        port: "22"
        source: "./var/export/xmltv.xml.gz"
        target: "/var/www/xmltv"
        
    - name: Sauvgarde ZIP sur serveur
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.pass }}
        port: "22"
        source: "./var/export/xmltv.zip"
        target: "/var/www/xmltv"
    
    - name: Sauvgarde GITHUB
      uses: EndBug/add-and-commit@v9
      with:
       message: 'Mises à jour des programmes'
      
   
