# This is a basic workflow that is manually triggered

name: Mise à jour des programmes TV

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  schedule:
    - cron: "0 6 * * *" # Runs at 06:00 AM (UTC),
    
jobs:
  # This workflow contains a single job called "greet"
  TV:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Installation de PHP et des extentions
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl, zip, mbstring, xml, json  
        
    - name: Mise à jour des programmes
      run: php example/script_all.php
    
    - name: Sauvgarde sur serveur
      run : |
        run: sudo sshpass -p "${{ secrets.pass }}" scp -o StrictHostKeyChecking=no -r ${{ secrets.USER }}@${{ secrets.IP }}:/var/export/xmltv.xml /var/www/xmltv/var/export 
        run: sudo sshpass -p "${{ secrets.pass }}" scp -o StrictHostKeyChecking=no -r ${{ secrets.USER }}@${{ secrets.IP }}:/var/export/xmltv.xml.gz /var/www/xmltv/var/export 
        run: sudo sshpass -p "${{ secrets.pass }}" scp -o StrictHostKeyChecking=no -r ${{ secrets.USER }}@${{ secrets.IP }}:/var/export/xmltv.zip /var/www/xmltv/var/export 

    - name: Sauvgarde GITHUB
      uses: EndBug/add-and-commit@v9
      with:
       message: 'Mises à jour des programmes'
      
   
