# This is a basic workflow that is manually triggered

name: Mise à jour des programmes TV

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]  

jobs:
  # This workflow contains a single job called "greet"
  TV:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Setup PHP with PECL extension
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: curl, zip, mbstring, xml, json  
    - name: Mise à jour des programmes
      run: php example/script_all.php
        
    - name: Modifiy the specific files using action
      uses: EndBug/add-and-commit@v9
      with:
       message: 'Mise en places des fichiers'
      
   
